# Generated by Django 4.2 on 2023-05-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="body",
            field=models.TextField(max_length=10000),
        ),
    ]
