# Generated by Django 4.2 on 2023-05-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_news_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="category",
            field=models.CharField(default="-", max_length=100),
        ),
        migrations.AddField(
            model_name="news",
            name="category_id",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="news",
            name="show",
            field=models.BooleanField(default=True),
        ),
    ]
