# Generated by Django 4.2 on 2023-05-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_news_category_news_category_id_news_show"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="image_url",
            field=models.CharField(default="-", max_length=200),
        ),
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
        migrations.AlterField(
            model_name="news",
            name="show",
            field=models.IntegerField(default=0),
        ),
    ]
