# Generated by Django 4.2 on 2023-05-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_news_image_url_alter_news_image_alter_news_show"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
