# Generated by Django 4.2 on 2023-05-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0008_news_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="o_category_id",
            field=models.IntegerField(default=1),
        ),
    ]
