# Generated by Django 4.2 on 2023-04-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="main",
            name="body",
        ),
        migrations.AddField(
            model_name="main",
            name="about",
            field=models.TextField(default="about"),
        ),
    ]
