# Generated by Django 4.2 on 2023-04-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_main_body_main_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="main",
            name="fb",
            field=models.CharField(default="https://www.facebook.com/", max_length=200),
        ),
        migrations.AddField(
            model_name="main",
            name="gh",
            field=models.CharField(default="https://github.com/", max_length=200),
        ),
        migrations.AddField(
            model_name="main",
            name="ig",
            field=models.CharField(
                default="https://www.instagram.com/", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="main",
            name="li",
            field=models.CharField(default="https://www.linkedin.com/", max_length=200),
        ),
        migrations.AddField(
            model_name="main",
            name="tw",
            field=models.CharField(default="https://twitter.com/", max_length=200),
        ),
        migrations.AddField(
            model_name="main",
            name="yt",
            field=models.CharField(default="https://www.youtube.com/", max_length=200),
        ),
    ]
