# Generated by Django 4.2 on 2023-04-08 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_main_fb_main_gh_main_ig_main_li_main_tw_main_yt"),
    ]

    operations = [
        migrations.RenameField(
            model_name="main",
            old_name="fb",
            new_name="facebook",
        ),
        migrations.RenameField(
            model_name="main",
            old_name="gh",
            new_name="github",
        ),
        migrations.RenameField(
            model_name="main",
            old_name="ig",
            new_name="instagram",
        ),
        migrations.RenameField(
            model_name="main",
            old_name="li",
            new_name="linkedin",
        ),
        migrations.RenameField(
            model_name="main",
            old_name="tw",
            new_name="twitter",
        ),
        migrations.RenameField(
            model_name="main",
            old_name="yt",
            new_name="youtube",
        ),
    ]
