# Generated by Django 4.2 on 2023-04-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_rename_fb_main_facebook_rename_gh_main_github_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="main",
            name="set_title",
            field=models.CharField(default="News Mag", max_length=200),
        ),
    ]
