# Generated by Django 4.2 on 2023-04-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_main_set_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="main",
            name="email",
            field=models.CharField(
                default="mailto:john.doe@example.com", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="main",
            name="link",
            field=models.CharField(default="https://example.com/", max_length=200),
        ),
        migrations.AddField(
            model_name="main",
            name="tel",
            field=models.CharField(default="tel:123456789", max_length=200),
        ),
    ]
