# Generated by Django 4.2 on 2023-10-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_main_email_main_link_main_tel"),
    ]

    operations = [
        migrations.AddField(
            model_name="main",
            name="image_name",
            field=models.TextField(default="image_name"),
        ),
        migrations.AddField(
            model_name="main",
            name="image_url",
            field=models.TextField(default="image_url"),
        ),
    ]
